version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - "DOMAIN_NAME=${DOMAIN_NAME}"
        - "CERTS_=${CERTS_}"
    # image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - net
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    # image: wordpress
    container_name: wordpress
    expose:
      - "9000"
    restart: always
    networks:
      - net
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    # image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    restart: always
    networks:
      - net
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql

# type filesystem???
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR}/mariadb/database
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DIR}/wordpress/web
      o: bind

networks:
  net:
    driver: bridge